spring:
  application:
    name: starter
  datasource:
    url: jdbc:postgresql://localhost:5432/app_starter
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
